version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9999:9999"
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "81:81"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app-net

networks:
  app-net:
